sudo: required
dist: trusty
services:
  - docker
language: rust

matrix:
  include:
    # Linux builds use the `rust-slave-dist` image so we link them against a
    # "super old glibc" to ensure that it runs on as many platforms as possible.
    - os: linux
      env: TARGET=i686-unknown-linux-gnu
           DOCKER=alexcrichton/rust-slave-dist:2015-10-20b
    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu
           DOCKER=alexcrichton/rust-slave-dist:2015-10-20b
           NO_ADD=1
           ALLOW_PR=1

    # Cross builds happen in the `rust-slave-linux-cross` image to ensure that
    # we use the right cross compilers for these targets. That image should
    # bundle all the gcc cross compilers to enable us to build OpenSSL
    - os: linux
      env: TARGET=arm-unknown-linux-gnueabi
           DOCKER=alexcrichton/rust-slave-linux-cross:2016-11-11
           SKIP_TESTS=1
    - os: linux
      env: TARGET=arm-unknown-linux-gnueabihf
           DOCKER=alexcrichton/rust-slave-linux-cross:2016-11-11
           SKIP_TESTS=1
    - os: linux
      env: TARGET=armv7-unknown-linux-gnueabihf
           DOCKER=alexcrichton/rust-slave-linux-cross:2016-11-11
           SKIP_TESTS=1
    - os: linux
      env: TARGET=aarch64-unknown-linux-gnu
           DOCKER=alexcrichton/rust-slave-linux-cross:2016-11-11
           SKIP_TESTS=1
    - os: linux
      env: TARGET=x86_64-unknown-freebsd
           DOCKER=alexcrichton/rust-slave-linux-cross:2016-11-11
           SKIP_TESTS=1
    - os: linux
      env: TARGET=x86_64-unknown-netbsd
           DOCKER=alexcrichton/rust-slave-linux-cross:2016-11-11
           SKIP_TESTS=1
    - os: linux
      env: TARGET=powerpc-unknown-linux-gnu
           DOCKER=alexcrichton/rust-slave-linux-cross:2016-11-11
           SKIP_TESTS=1
    - os: linux
      env: TARGET=powerpc64-unknown-linux-gnu
           DOCKER=powerpc64-unknown-linux-gnu
           SKIP_TESTS=1
    - os: linux
      env: TARGET=powerpc64le-unknown-linux-gnu
           DOCKER=powerpc64le-unknown-linux-gnu
           SKIP_TESTS=1
    - os: linux
      env: TARGET=mips-unknown-linux-gnu
           DOCKER=mips-unknown-linux-gnu
           SKIP_TESTS=1
    - os: linux
      env: TARGET=mipsel-unknown-linux-gnu
           DOCKER=mipsel-unknown-linux-gnu
           SKIP_TESTS=1
    - os: linux
      env: TARGET=mips64-unknown-linux-gnuabi64
           DOCKER=mips64-unknown-linux-gnuabi64
           SKIP_TESTS=1
    - os: linux
      env: TARGET=mips64el-unknown-linux-gnuabi64
           DOCKER=mips64el-unknown-linux-gnuabi64
           SKIP_TESTS=1
    - os: linux
      env: TARGET=s390x-unknown-linux-gnu
           DOCKER=s390x-unknown-linux-gnu
           SKIP_TESTS=1

    # Android use a local docker image
    - os: linux
      env: TARGET=arm-linux-androideabi
           DOCKER=android
           SKIP_TESTS=1
    - os: linux
      env: TARGET=armv7-linux-androideabi
           DOCKER=android
           SKIP_TESTS=1
    - os: linux
      env: TARGET=aarch64-linux-android
           DOCKER=android
           SKIP_TESTS=1
    - os: linux
      env: TARGET=i686-linux-android
           DOCKER=android
           SKIP_TESTS=1
    - os: linux
      env: TARGET=x86_64-linux-android
           DOCKER=android
           SKIP_TESTS=1

    # On OSX we want to target 10.7 so we ensure that the appropriate
    # environment variable is set to tell the linker what we want.
    - os: osx
      env: TARGET=i686-apple-darwin
           MACOSX_DEPLOYMENT_TARGET=10.7
    - os: osx
      env: TARGET=x86_64-apple-darwin
           MACOSX_DEPLOYMENT_TARGET=10.7
           NO_ADD=1

cache:
  # We're going to download things we don't necessarily want to cache into the `target` directory, so
  # don't use travis's native `cargo` caching, which just grabs the whole folder.
  directories:
    - target/$TARGET/openssl/openssl-install
    - target/release/deps

branches:
  only:
    - master
    - stable
    - auto

install:
  - if [ -z "$NO_ADD" ]; then rustup target add $TARGET; fi

script:
  - mkdir -p target/$TARGET;
  - >
    if [[ "$TRAVIS_PULL_REQUEST" == "false" || "$ALLOW_PR" == "1" ]]; then
        if [ ! -z "$DOCKER" ]; then
            sh ci/build-run-docker.sh "$DOCKER" "$TARGET" "$SKIP_TESTS";
        else
            PATH=$HOME/rust/bin:$PATH sh ci/run.sh;
        fi
    else
        echo 'skipping build';
    fi

before_deploy:
  - bash ci/prepare-deploy-travis.sh

deploy:
  - provider: s3
    bucket: dev-static-rust-lang-org
    skip_cleanup: true
    local_dir: deploy
    upload_dir: rustup
    acl: public_read
    region: us-west-1
    access_key_id: AKIAIZT5ZFS5N2VNRGPA
    secret_access_key:
      secure: "CGFWEhkk6siQxW24zJqlXRC4WLQPqXRJ5Rqa6rQNErotorRUn0DnPB+4zYW4KvMTDkv5pPwEv8P6b0IwbY8ZrS7ChfZ6t89xTvuklxsb8PlMwaDXWqkP5cCBT4B/e1S81xSI7ptkQ7Te5bcVbPMVE3MuGYtzhgIaYu+RZMLHSteY2TGnHid7ErmZKmvGoRqootEHYRo4Pv2s2ydZaalzrt8I5uGQPzesJc2T8xWS8VcFAGJTy4p59h5d6Btlo2a5L3Oc8kMLDzsxzwBbrNXQjF7oLZw7g1uf1A7iBrJGsv61GCnggl4+gtEt/BFQ8mtknBLXv3kXBfvrj35YnHAZosZWufSOgsQ9HB7ELjVhRhGRFX2BNKH1Gm/qM0j7WenD3vhOCTzMW21xqEvgY7+KIvyb9XLla7du/0/rZnDoBnCbZNpBOU5NqOV0y6MN6NDL5g168N7M30BeEEcJjbLEXtUTlCp/6jzZj3frDezJNJypniqwRfacf0yKNykVsnpqpcPmQfvxk2I/1BjdukLM5WifAgTEy9IG2/PBUIWr5ikAlhpACxmuKrlExJpOmZRMRjjRjI8tw8bSKu00SbeYT6PO0xazP9oJYKtWi5vkvM9U4R7udeYHTJFAMkeASpOO4Ss6f+dXQzm7OWqFu07Ffm9zHh+WX95PXonlzauEQ1I="
    on:
      branch: stable

# FIXME: I don't know if this really works
after_deploy:
  - sudo pip install awscli
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --paths "rustup/$TARGET/* rustup/dev/$TARGET/* rustup/www/* rustup/dev/www/* rustup/* rustup/dev/*"
