language: rust
rust:
  - nightly

env:
  - TARGET=x86_64-unknown-linux-gnu
    BITS=64

install: |
  git config --global user.email "diggsey@googlemail.com" && \
  git config --global user.name "Diggory Blake (via Travis CI)" && \
  git config --global push.default simple
  
script: |
  export OPENSSL_STATIC=1 && \
  cargo build --release --verbose && \
  cargo test --verbose

after_success: |
  git config --global credential.helper store && \
  echo "https://${TOKEN}:x-oauth-basic@github.com" >> ~/.git-credentials && \
  cargo doc \
  && echo '<meta http-equiv=refresh content=0;url=multirust/index.html>' > target/doc/index.html && \
  sudo pip install ghp-import && \
  ghp-import -n target/doc && \
  git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages && \
  git submodule init && \
  git submodule update --depth 1 --remote && \
  mkdir -p "binaries/$TARGET" && \
  find "target/release/" -maxdepth 1 -type f -exec cp {} "binaries/$TARGET" \; && \
  git rev-parse HEAD > "binaries/$TARGET/commit.txt" && \
  cd binaries && \
  git checkout master && \
  git add . && \
  git commit -m "Auto-update $TARGET binaries (Travis CI)" && \
  for i in {1..5}; do ./push-changes.sh && break; done
