matrix:
  include:
    - os: linux
      env: TARGET=i686-unknown-linux-gnu BITS=32
    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu BITS=64
    - os: osx
      env: TARGET=i686-apple-darwin BITS=32 MACOSX_DEPLOYMENT_TARGET=10.7
    - os: osx
      env: TARGET=x86_64-apple-darwin BITS=64 MACOSX_DEPLOYMENT_TARGET=10.7
  allow_failures:
    - os: osx

git:
  submodules: false

sudo: required
install:
  - git config --global user.email "diggsey@googlemail.com"
  - git config --global user.name "Diggory Blake (via Travis CI)"
  - git config --global push.default simple
  - mkdir -p ~/rust
  - echo -e "\033[33;1mDownloading Rust\033[0m"
  - curl -sL http://static.rust-lang.org/dist/rust-nightly-$TARGET.tar.gz | tar --strip-components=1 -C ~/rust -xzf -
  - if [ "$TARGET" == "i686-unknown-linux-gnu" ]; then
      sudo apt-get update;
      sudo apt-get install libc6-dev:i386 libstdc++6:i386 zlib1g-dev:i386 libssl-dev:i386 pkg-config:i386 gcc-multilib;
    fi
  - echo -e "\033[33;1mInstalling Rust\033[0m"
  - sudo ~/rust/install.sh

script:
  - export OPENSSL_STATIC=1
  - cargo build --release --verbose
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      find "target/release/" -maxdepth 1 -type f -exec sh -c 'shasum -a 256 -b "{}" | cut -d\  -f1 > "{}.sha256"' \;;
    else
      find "target/release/" -maxdepth 1 -type f -exec sh -c 'sha256sum -b "{}" | cut -d\  -f1 > "{}.sha256"' \;;
    fi
  - cargo test --verbose
  - tests/cli.sh

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      git config --global credential.helper store;
      echo "https://${TOKEN}:x-oauth-basic@github.com" >> ~/.git-credentials;
      if [ "$TARGET" == "x86_64-unknown-linux-gnu" ]; then
        cargo doc;
        echo '<meta http-equiv=refresh content=0;url=multirust/index.html>' > target/doc/index.html;
        sudo pip install ghp-import;
        ghp-import -n target/doc;
        git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages;
      fi;
      if [ "$TRAVIS_BRANCH" == "master" ]; then
        bin=./binaries/$TARGET;
      else
        bin=./binaries/$TRAVIS_BRANCH/$TARGET;
      fi;
      git submodule init;
      git submodule update --depth 1 --remote;
      mkdir -p "$bin";
      rm $bin/*;
      find "target/release/" -maxdepth 1 -type f -exec cp "{}" "$bin" \;;
      git rev-parse HEAD > "$bin/commit.txt";
      cd binaries;
      git checkout master;
      git add -A;
      git commit -m "Auto-update $TRAVIS_BRANCH/$TARGET binaries (Travis CI)";
      for i in {1..5}; do ./push-changes.sh && break; done;
    fi
