environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: i686-pc-windows-msvc
  - TARGET: x86_64-pc-windows-gnu
    BITS: 64
  - TARGET: i686-pc-windows-gnu
    BITS: 32
  access_token:
    secure: q8Wqx0brgfpOYFQqWauvucE2h0o1WYb41a3gKaCKV9QiE4eTz6qLNlqyC3mdsp4Q
branches:
  only:
    - master
    - stable
    - auto

install:
  - ps: |
      # Install Rust
      Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe" -FileName "rust-nightly.exe"
      .\rust-nightly.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
      $env:PATH="$env:PATH;C:\rust\bin"

      New-Item .cargo -type directory
      Copy-Item ci/appveyor-cargo-config.toml .cargo/config

      # For -gnu builds
      if ($env:TARGET -match "-gnu$") {
        $env:PATH="$env:PATH;C:\msys64\mingw${env:BITS}\bin"
      }

      # For -msvc builds
      if ($env:TARGET -match "-msvc$") {
        Start-FileDownload "http://www.npcglib.org/~stathis/downloads/openssl-1.0.2d-vs2015.7z" -FileName "openssl.7z"
        7z x openssl.7z -o"C:\OpenSSL" | Out-Null
      }

      # Print version info
      rustc -vV
      cargo -vV

build: false

test_script:
  - cargo build  --release
  - cargo test --release -p rustup-dist
  - cargo test --release

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/9907ad94eb7a5ff291c3

after_test:
  - powershell -File ci/prepare-deploy-appveyor.ps1

artifacts:
  - path: dist\$(TARGET)\rustup-setup.exe
    name: rustup-setup
  - path: dist\$(TARGET)\rustup-setup.exe.sha256
    name: rustup-setup-sha

deploy:
  - provider: S3
    skip_cleanup: true
    access_key_id: AKIAIZT5ZFS5N2VNRGPA
    secret_access_key:
      secure: viw7GCfVF0QlY0fghoxO3Lux/Wo4u6PxxgUwEq5cs4w69tlv9KzIIw74Nc7KJdgt
    bucket: dev-static-rust-lang-org
    set_public: true
    region: us-west-1
    artifact: rustup-setup,rustup-setup-sha
    folder: rustup
    on:
      branch: master

  - provider: S3
    skip_cleanup: true
    access_key_id: AKIAIZT5ZFS5N2VNRGPA
    secret_access_key:
      secure: viw7GCfVF0QlY0fghoxO3Lux/Wo4u6PxxgUwEq5cs4w69tlv9KzIIw74Nc7KJdgt
    bucket: static-rust-lang-org
    set_public: true
    region: us-west-1
    artifact: rustup-setup,rustup-setup-sha
    folder: rustup
    on:
      branch: stable
