environment:
  RUSTFLAGS: -Zunstable-options -Ctarget-feature=+crt-static
  matrix:
  - TARGET: i686-pc-windows-msvc
    BUILD_MSI: 1
  - TARGET: i686-pc-windows-gnu
    MINGW_URL: https://s3.amazonaws.com/rust-lang-ci
    MINGW_ARCHIVE: i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z
    MINGW_DIR: mingw32
  - TARGET: x86_64-pc-windows-gnu
    MSYS_BITS: 64
  - TARGET: i686-pc-windows-msvc
  - TARGET: x86_64-pc-windows-msvc
  access_token:
    secure: q8Wqx0brgfpOYFQqWauvucE2h0o1WYb41a3gKaCKV9QiE4eTz6qLNlqyC3mdsp4Q
branches:
  only:
    - master
    - stable
    - auto

install:
  # Install rust, x86_64-pc-windows-msvc host
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-toolchain=nightly-x86_64-pc-windows-msvc
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin

  # Install the target we're compiling for
  - if NOT "%TARGET%" == "x86_64-pc-windows-msvc" rustup target add %TARGET%

  # Use the system msys if we can
  - if defined MSYS_BITS set PATH=C:\msys64\mingw%MSYS_BITS%\bin;C:\msys64\usr\bin;%PATH%

  # download a custom compiler otherwise
  - if defined MINGW_URL appveyor DownloadFile %MINGW_URL%/%MINGW_ARCHIVE%
  - if defined MINGW_URL 7z x -y %MINGW_ARCHIVE% > nul
  - if defined MINGW_URL set PATH=%CD%\%MINGW_DIR%\bin;C:\msys64\usr\bin;%PATH%

  # set cargo features for MSI if requested (otherwise empty string)
  - set FEATURES=
  - if defined BUILD_MSI set FEATURES=--features msi-installed

  # let's see what we got
  - where gcc rustc cargo
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - cargo build --release --target %TARGET% %FEATURES%
  - cargo test --release -p rustup-dist --target %TARGET%
  - cargo test --release --target %TARGET% %FEATURES%
  - ps: |
      if($env:BUILD_MSI) {
        cd src\rustup-win-installer
        cargo build --release --target $env:TARGET
        cd msi
        .\build.ps1 -Target $env:TARGET
        cd ..\..\..
        if($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
      }

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/9907ad94eb7a5ff291c3

after_test:
  - powershell -File ci/prepare-deploy-appveyor.ps1

artifacts:
  - path: dist\$(TARGET)\rustup-init.exe
    name: rustup-init
  - path: dist\$(TARGET)\rustup-init.exe.sha256
    name: rustup-init-sha
  - path: dist\$(TARGET)\rustup-setup.exe
    name: rustup-setup
  - path: dist\$(TARGET)\rustup-setup.exe.sha256
    name: rustup-setup-sha

deploy:
  - provider: S3
    skip_cleanup: true
    access_key_id: AKIAIZT5ZFS5N2VNRGPA
    secret_access_key:
      secure: viw7GCfVF0QlY0fghoxO3Lux/Wo4u6PxxgUwEq5cs4w69tlv9KzIIw74Nc7KJdgt
    bucket: dev-static-rust-lang-org
    set_public: true
    region: us-west-1
    artifact: rustup-init,rustup-init-sha,rustup-setup,rustup-setup-sha
    folder: rustup
    on:
      branch: stable
