[package]

name = "rustup"
version = "0.1.6"
authors = [ "Diggory Blake <diggsey@googlemail.com>" ]
description = "multirust in rust - manage multiple rust installations with ease"

documentation = "http://diggsey.github.io/multirust-rs/multirust/index.html"
homepage = "https://github.com/rust-lang-nursery/multirust-rs"
repository = "https://github.com/rust-lang-nursery/multirust-rs"

readme = "README.md"

keywords = ["multirust", "install", "proxy"]

license = "MIT OR Apache-2.0"

[dependencies]
rustup-dist = { path = "src/rustup-dist" }
rustup-utils = { path = "src/rustup-utils" }
clap = "2.2.4"
regex = "0.1.41"
openssl = "0.7.2"
hyper = "0.7.0"
term = "0.4.4"
itertools = "0.4.1"
time = "0.1.34"
tempdir = "0.3.4"
libc = "0.2.0"
rand = "0.3.11"
scopeguard = "0.1.2"

[target.x86_64-pc-windows-gnu.dependencies]
winapi = "0.2.4"
winreg = "0.3.2"
user32-sys = "0.1.2"
kernel32-sys = "0.2.1"

[target.x86_64-pc-windows-msvc.dependencies]
winapi = "0.2.4"
winreg = "0.3.2"
user32-sys = "0.1.2"
kernel32-sys = "0.2.1"

[target.i686-pc-windows-gnu.dependencies]
winapi = "0.2.4"
winreg = "0.3.2"
user32-sys = "0.1.2"
kernel32-sys = "0.2.1"

[target.i686-pc-windows-msvc.dependencies]
winapi = "0.2.4"
winreg = "0.3.2"
user32-sys = "0.1.2"
kernel32-sys = "0.2.1"

[dev-dependencies]
rustup-mock = { path = "src/rustup-mock" }
lazy_static = "0.1.15"

[lib]
name = "rustup"
path = "src/rustup/lib.rs"
test = false # no unit tests

[[bin]]
name = "rustup-init"
path = "src/rustup-cli/main.rs"
test = false # no unit tests
