[package]

name = "multirust-rs"
version = "0.0.1"
authors = [ "Diggory Blake <diggsey@googlemail.com>" ]
description = "multirust in rust - manage multiple rust installations with ease"

documentation = "http://diggsey.github.io/multirust-rs/multirust/index.html"
homepage = "https://github.com/Diggsey/multirust-rs"
repository = "https://github.com/Diggsey/multirust-rs"

readme = "README.md"

keywords = ["multirust", "install", "proxy"]

license = "MIT"

[dependencies]
clap = { version = "1.4.2", features = ["yaml"] }
regex = "0.1.41"
rand = "0.3.11"
hyper = "0.6.14"

[lib]
name = "multirust"

[[bin]]
name = "multirust-rs"
