[package]

name = "rustup"
version = "1.5.0"
authors = [ "Diggory Blake <diggsey@googlemail.com>" ]
description = "Manage multiple rust installations with ease"

documentation = "http://rust-lang-nursery.github.io/rustup.rs/rustup/index.html"
homepage = "https://github.com/rust-lang-nursery/rustup.rs"
repository = "https://github.com/rust-lang-nursery/rustup.rs"

readme = "README.md"

keywords = ["rustup", "multirust", "install", "proxy"]

license = "MIT OR Apache-2.0"

build = "build.rs"

[features]

default = ["curl-backend", "hyper-backend"]

curl-backend = ["download/curl-backend"]
hyper-backend = ["download/hyper-backend"]
rustls-backend = ["download/rustls-backend"]

# Include in the default set to disable self-update and uninstall.
no-self-update = []

# Used to change behavior of self-update and uninstall if installed via MSI
msi-installed = []

[dependencies]
rustup-dist = { path = "src/rustup-dist" }
rustup-utils = { path = "src/rustup-utils" }
download = { path = "src/download" }
error-chain = "0.10"
clap = "2.18.0"
regex = "0.2"
url = "1.1.0"
term = "0.4.4"
itertools = "0.6"
time = "0.1.34"
tempdir = "0.3.4"
tempfile = "2.1.4"
libc = "0.2.0"
rand = "0.3.11"
markdown = "0.2"
rustc-serialize = "0.3"
scopeguard = "0.3"
sha2 = "0.6.0"
toml = "0.1"
wait-timeout = "0.1.5"

[target."cfg(windows)".dependencies]
winapi = "0.2.8"
winreg = "0.4.0"
user32-sys = "0.2.0"
kernel32-sys = "0.2.1"
gcc = "0.3.50"
psapi-sys = "0.1"

[dev-dependencies]
rustup-mock = { path = "src/rustup-mock", version = "1.1.0" }
lazy_static = "0.2"

[workspace]
members = ["src/rustup-win-installer"]

[lib]
name = "rustup"
path = "src/rustup/lib.rs"
test = false # no unit tests

[[bin]]
name = "rustup-init"
path = "src/rustup-cli/main.rs"
test = false # no unit tests
