[package]

name = "rustup"
version = "1.17.0"
edition = "2018"
authors = [ "Diggory Blake <diggsey@googlemail.com>" ]
description = "Manage multiple rust installations with ease"

documentation = "http://rust-lang.github.io/rustup.rs/rustup/index.html"
homepage = "https://github.com/rust-lang/rustup.rs"
repository = "https://github.com/rust-lang/rustup.rs"

readme = "README.md"

keywords = ["rustup", "multirust", "install", "proxy"]

license = "MIT OR Apache-2.0"

build = "build.rs"

[features]

default = ["curl-backend", "reqwest-backend"]

curl-backend = ["download/curl-backend"]
reqwest-backend = ["download/reqwest-backend"]
vendored-openssl = ['openssl/vendored']

# Include in the default set to disable self-update and uninstall.
no-self-update = []

[dependencies]
dirs = "1.0"
download = { path = "download" }
clap = "2.18.0"
error-chain = "0.12.0"
flate2 = "1.0.1"
itertools = "0.7.6"
libc = "0.2.0"
markdown = "0.2"
ole32-sys = "0.2.0"
rand = "0.5.2"
regex = "1.0.1"
remove_dir_all = "0.5.1"
same-file = "1.0"
semver = "0.9.0"
scopeguard = "0.3"
sha2 = "0.7.0"
tar = "0.4.0"
tempdir = "0.3.4"
term = "0.5.1"
time = "0.1.34"
toml = "0.4"
url = "1.1.0"
wait-timeout = "0.1.5"
walkdir = "2.0"
xz2 = "0.1.3"
openssl = { version = '0.10.15', optional = true }

[target."cfg(windows)".dependencies]
winapi = { version = "0.3", features = ["combaseapi", "errhandlingapi", "fileapi", "handleapi", "ioapiset", "jobapi", "jobapi2", "minwindef", "processthreadsapi", "psapi", "shlobj", "shtypes", "synchapi", "sysinfoapi", "tlhelp32", "userenv", "winbase", "winerror", "winioctl", "winnt", "winuser"] }
winreg = "0.5.0"
gcc = "0.3.50"

[dev-dependencies]
lazy_static = "1.0.0"

[workspace]
members = ["download"]

[lib]
name = "rustup"
path = "src/lib.rs"
test = false # no unit tests

[[bin]]
name = "rustup-init"
path = "src/cli/main.rs"
test = false # no unit tests

[profile.release]
lto = true
codegen-units = 1
