[package]
name = "rustup"
version = "1.21.1"
authors = [ "Daniel Silverstone <dsilvers@digital-scurf.org>", "Diggory Blake <diggsey@googlemail.com>" ]
build = "build.rs"
edition = "2018"
homepage = "https://github.com/rust-lang/rustup"
keywords = ["rustup", "multirust", "install", "proxy"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang/rustup"
description = "Manage multiple rust installations with ease"

[features]
default = ["curl-backend", "reqwest-backend"]
curl-backend = ["download/curl-backend"]
reqwest-backend = ["download/reqwest-backend"]
vendored-openssl = ['openssl/vendored']
# Include in the default set to disable self-update and uninstall.
no-self-update = []

# Sorted by alphabetic order
[dependencies]
chrono = "0.4"
clap = "2"
download = { path = "download" }
error-chain = "0.12"
effective-limits = "0.4"
flate2 = "1"
git-testament = "0.1.4"
home = "0.5"
lazy_static = "1"
libc = "0.2"
opener = "0.4.0"
# Used by `curl` or `reqwest` backend although it isn't imported
# by our rustup.
openssl = { version = "0.10", optional = true }
pulldown-cmark = { version = "0.7", default-features = false }
rand = "0.7"
regex = "1"
remove_dir_all = "0.5.1"
same-file = "1"
scopeguard = "1"
semver = "0.9"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.8"
strsim = "0.9.1"
tar = "0.4.26"
tempfile = "3.1"
# FIXME(issue #1788)
term = "=0.5.1"
threadpool = "1"
toml = "0.5"
url = "2.1"
wait-timeout = "0.2"
xz2 = "0.1.3"
pgp = { version = "0.5", default-features = false}

[dependencies.retry]
version = "1"
default-features = false

[dependencies.rs_tracing]
version = "1.0.1"
features = ["rs_tracing"]

[target."cfg(windows)".dependencies]
cc = "1"
winreg = "0.6"

[target."cfg(windows)".dependencies.winapi]
version = "0.3"
features = [
    "combaseapi",
    "errhandlingapi",
    "fileapi",
    "handleapi",
    "ioapiset",
    "jobapi",
    "jobapi2",
    "minwindef",
    "processthreadsapi",
    "psapi",
    "shlobj",
    "shtypes",
    "synchapi",
    "sysinfoapi",
    "tlhelp32",
    "userenv",
    "winbase",
    "winerror",
    "winioctl",
    "winnt",
    "winuser",
]

[dev-dependencies]
walkdir = "2"

[workspace]
members = ["download"]

[lib]
name = "rustup"
path = "src/lib.rs"
test = false # no unit tests

[[bin]]
name = "rustup-init"
path = "src/cli/main.rs"

[profile.release]
lto = true
codegen-units = 1

# Reduce build time by setting proc-macro crates non optimized.
[profile.release.build-override]
opt-level = 0
