[package]

name = "rustup"
version = "0.1.9"
authors = [ "Diggory Blake <diggsey@googlemail.com>" ]
description = "multirust in rust - manage multiple rust installations with ease"

documentation = "http://rust-lang-nursery.github.io/rustup.rs/rustup/index.html"
homepage = "https://github.com/rust-lang-nursery/rustup.rs"
repository = "https://github.com/rust-lang-nursery/rustup.rs"

readme = "README.md"

keywords = ["multirust", "install", "proxy"]

license = "MIT OR Apache-2.0"

build = "build.rs"

[dependencies]
rustup-dist = { path = "src/rustup-dist", version = "0.1.9" }
rustup-utils = { path = "src/rustup-utils", version = "0.1.9" }
error-chain = { path = "src/error-chain", version = "0.1.9" }
clap = "2.2.4"
regex = "0.1.41"
url = "1.1.0"
term = "0.4.4"
itertools = "0.4.1"
time = "0.1.34"
tempdir = "0.3.4"
libc = "0.2.0"
rand = "0.3.11"
scopeguard = "0.1.2"
rustc-serialize = "0.3"
sha2 = "0.1.2"

[target."cfg(windows)".dependencies]
winapi = "0.2.4"
winreg = "0.3.2"
user32-sys = "0.1.2"
kernel32-sys = "0.2.1"

[dev-dependencies]
rustup-mock = { path = "src/rustup-mock", version = "0.1.9" }
lazy_static = "0.1.15"

[lib]
name = "rustup"
path = "src/rustup/lib.rs"
test = false # no unit tests

[[bin]]
name = "rustup-init"
path = "src/rustup-cli/main.rs"
test = false # no unit tests
