[package]
name = "rustup"
version = "1.18.2"
authors = [ "Diggory Blake <diggsey@googlemail.com>" ]
build = "build.rs"
documentation = "https://rust-lang.github.io/rustup.rs/rustup/index.html"
edition = "2018"
homepage = "https://github.com/rust-lang/rustup.rs"
keywords = ["rustup", "multirust", "install", "proxy"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang/rustup.rs"
description = "Manage multiple rust installations with ease"

[features]
default = ["curl-backend", "reqwest-backend"]
curl-backend = ["download/curl-backend"]
reqwest-backend = ["download/reqwest-backend"]
vendored-openssl = ['openssl/vendored']
# Include in the default set to disable self-update and uninstall.
no-self-update = []

# Sorted by alphabetic order
[dependencies]
clap = "2"
dirs = "1"
download = { path = "download" }
error-chain = "0.12"
flate2 = "1"
git-testament = "0.1.4"
lazy_static = "1"
libc = "0.2"
markdown = "0.2"
opener = "0.4.0"
# Used by `curl` or `reqwest` backend although it isn't imported
# by our rustup.
openssl = { version = "0.10", optional = true }
rand = "0.6"
regex = "1"
remove_dir_all = "0.5.1"
same-file = "1"
scopeguard = "1"
semver = "0.9"
sha2 = "0.8"
strsim = "0.9.1"
tar = "0.4"
tempdir = "0.3.4"
# FIXME(issue #1788)
term = "=0.5.1"
time = "0.1.34"
toml = "0.5"
url = "1"
wait-timeout = "0.2"
walkdir = "2"
xz2 = "0.1.3"

[target."cfg(windows)".dependencies]
cc = "1"
winreg = "0.6"

[target."cfg(windows)".dependencies.winapi]
version = "0.3"
features = [
    "combaseapi",
    "errhandlingapi",
    "fileapi",
    "handleapi",
    "ioapiset",
    "jobapi",
    "jobapi2",
    "minwindef",
    "processthreadsapi",
    "psapi",
    "shlobj",
    "shtypes",
    "synchapi",
    "sysinfoapi",
    "tlhelp32",
    "userenv",
    "winbase",
    "winerror",
    "winioctl",
    "winnt",
    "winuser",
]

[workspace]
members = ["download"]

[lib]
name = "rustup"
path = "src/lib.rs"
test = false # no unit tests

[[bin]]
name = "rustup-init"
path = "src/cli/main.rs"

[profile.release]
lto = true
codegen-units = 1
