[package]

name = "rustup-utils"
version = "0.1.11"
authors = [ "Diggory Blake <diggsey@googlemail.com>" ]
description = "multirust in rust - manage multiple rust installations with ease"

documentation = "http://rust-lang-nursery.github.io/rustup.rs/rustup_utils/index.html"
homepage = "https://github.com/rust-lang-nursery/rustup.rs"
repository = "https://github.com/rust-lang-nursery/rustup.rs"

license = "MIT OR Apache-2.0"

[dependencies]
rand = "0.3.11"
scopeguard = "0.1.2"
error-chain = { path = "../error-chain", version = "0.1.11" }
libc = "0.2.0"
rustc-serialize = "0.3.19"
sha2 = "0.1.2"
curl = { git = "https://github.com/alexcrichton/curl-rust", branch = "rewrite" }
url = "1.1"

[target."cfg(windows)".dependencies]
winapi = "0.2.4"
winreg = "0.3.2"
shell32-sys = "0.1.1"
ole32-sys = "0.2.0"
kernel32-sys = "0.2.1"
advapi32-sys = "0.2.0"
userenv-sys = "0.2.0"
