[book]
title = "The rustup book"
authors = ["The Rust Project Developers"]

[output.html]
git-repository-url = "https://github.com/rust-lang/rustup/tree/master/doc"
site-url = "https://rust-lang.github.io/rustup/"
