[package]

name = "download"
version = "0.3.0"
authors = [ "Brian Anderson <banderson@mozilla.com>" ]

license = "MIT/Apache-2.0"

[features]

default = ["hyper-backend"]

curl-backend = ["curl"]
hyper-backend = ["hyper", "env_proxy", "native-tls", "openssl-sys"]
rustls-backend = ["hyper", "env_proxy", "rustls", "lazy_static", "ca-loader"]

[dependencies]
error-chain = "0.4.0"
url = "1.1"
curl = { version = "0.3", optional = true }
lazy_static = { version = "0.2", optional = true }

[dependencies.hyper]
version = "0.9.8"
default-features = false
optional = true

[dependencies.env_proxy]
version = "0.1.1"
optional = true

[dependencies.native-tls]
git = "https://github.com/sfackler/rust-native-tls.git"
optional = true

[target.'cfg(not(any(target_os = "windows", target_os = "macos")))'.dependencies]
openssl-sys = { version = "0.7.11", optional = true }

[dependencies.rustls]
version = "0.1.2"
optional = true

[dependencies.ca-loader]
path = "../ca-loader"
version = "0.1.0"
optional = true
